import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SessionProviderWrapper from "./SessionProviderWrapper";
import "./globals.css";
import { Instagram, Facebook, Twitter } from "lucide-react";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen flex flex-col`}
      >
        <SessionProviderWrapper>
          <Navbar />
          <main className="flex-1">{children}</main>
          <footer className="w-full bg-background text-foreground py-12 mt-16 border-t border-border">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                <div>
                  <h3 className="text-2xl font-bold mb-4">TrendyWear</h3>
                  <p className="text-muted-foreground mb-4">
                    Your one-stop shop for the latest fashion trends at unbeatable
                    prices.
                  </p>
                  <div className="flex space-x-4">
                    <a
                      href="#"
                      className="text-foreground/70 hover:text-foreground transition-colors"
                    >
                      FB
                    </a>
                    <a
                      href="#"
                      className="text-foreground/70 hover:text-foreground transition-colors"
                    >
                      TW
                    </a>
                    <a
                      href="#"
                      className="text-foreground/70 hover:text-foreground transition-colors"
                    >
                      IG
                    </a>
                  </div>
                </div>
                <div>
                  <h4 className="text-lg font-semibold mb-4">Customer Service</h4>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>
                      <a
                        href="#"
                        className="hover:text-foreground transition-colors"
                      >
                        Contact Us
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-foreground transition-colors"
                      >
                        Shipping Policy
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-foreground transition-colors"
                      >
                        Return Policy
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-foreground transition-colors"
                      >
                        FAQ
                      </a>
                    </li>
                  </ul>
                </div>
                <div>
                  <h4 className="text-lg font-semibold mb-4">Company</h4>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>
                      <a
                        href="#"
                        className="hover:text-foreground transition-colors"
                      >
                        About Us
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-foreground transition-colors"
                      >
                        Careers
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-foreground transition-colors"
                      >
                        Press
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-foreground transition-colors"
                      >
                        Blog
                      </a>
                    </li>
                  </ul>
                </div>
                <div>
                  <h4 className="text-lg font-semibold mb-4">Subscribe</h4>
                  <p className="text-muted-foreground mb-4">
                    Get updates about new arrivals and special offers.
                  </p>
                  <div className="flex">
                    <input
                      type="email"
                      placeholder="Enter your email"
                      className="w-full px-4 py-2 rounded-l-md bg-muted border border-border focus:outline-none focus:ring-2 focus:ring-pink-500"
                    />
                    <button className="px-4 py-2 bg-pink-600 text-white rounded-r-md hover:bg-pink-700">
                      Subscribe
                    </button>
                  </div>
                </div>
              </div>
              <div className="mt-8 pt-8 border-t border-border text-muted-foreground text-sm text-center">
                © {new Date().getFullYear()} TrendyWear. All rights reserved.
              </div>
            </div>
          </footer>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
